[package]
name = "fusion-weixin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = true

[lints]
workspace = true

[dependencies]
aes.workspace = true
base64.workspace = true
cbc.workspace = true
fusion-security = { workspace = true, features = ["with-wechat"] }
hex.workspace = true
hmac.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
zeroize.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "net", "io-util"] }
