//! Orchestration commands and outcomes — the framework-facing shape of "start a workflow" /
//! "signal a workflow". Proto, HTTP and CLI surfaces are adapter-owned (`hetuflow.md` §10); these
//! types carry only what the engine needs.

use hetuflow_core::{ActivityInstance, DefinitionSnapshot, ScopeFilter, SignalType, WorkflowInstance};
use serde::{Deserialize, Serialize};

/// Terminal business side effect: enqueued as a `business_callback` outbox intent when the
/// instance completes with `approved`, and `side_effects_executed` flips only after the handler
/// confirms success.
///
/// This is an *instance*-level intent, not a node-level one: `NodeKind` has no BusinessCallback
/// variant, while `BusinessCallbackPayload` carries `business_type` / `business_key` — the
/// framework's business callback is by construction the flow's terminal effect.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TerminalCallback {
  pub handler_type: String,
  pub payload: serde_json::Value,
}

/// Start a workflow instance on one business object.
#[derive(Debug, Clone)]
pub struct StartCommand {
  pub tenant_id: i64,
  pub facility_id: uuid::Uuid,
  /// The published definition's id (opaque to the framework; the adapter's design-time id).
  pub definition_id: uuid::Uuid,
  /// The immutable snapshot bound to this instance. Validated before any write.
  pub snapshot: DefinitionSnapshot,
  /// Human-facing reference number, generated by the adapter.
  pub reference_no: String,
  pub business_type: String,
  pub business_key: String,
  /// Initial context (guard / items_path evaluation input).
  pub context: Option<serde_json::Value>,
  pub terminal_callback: Option<TerminalCallback>,
}

/// Outcome of [`crate::WorkflowService::start`].
#[derive(Debug, Clone)]
pub struct StartOutcome {
  pub instance: WorkflowInstance,
  /// `false` = an active instance for this `(business_type, business_key)` already existed and is
  /// returned unchanged (idempotent start, never a second instance and never an error).
  pub created: bool,
  pub active_activities: Vec<ActivityInstance>,
}

/// Advance a workflow instance with one signal.
#[derive(Debug, Clone)]
pub struct SignalCommand {
  /// Caller visibility, already derived from the adapter's trusted context.
  pub scope: ScopeFilter,
  pub instance_id: uuid::Uuid,
  pub signal: SignalType,
  /// Explicit target; required while several activities are active in parallel.
  pub activity_id: Option<uuid::Uuid>,
  /// Caller idempotency key (required — `hetuflow.md` §4).
  pub idempotency_key: String,
  /// Acting user id; `0` = system.
  pub actor_user_id: i64,
  pub review_notes: Option<String>,
  /// Required for `EventReceived`: MUST equal the target EventWait node's `event_type`.
  pub event_type: Option<String>,
  /// Target assignee for `Claimed` / `Reassigned`.
  pub assignee_id: Option<i64>,
  /// Runtime context write-back payload; only keys declared in the node's `context_writes`
  /// are merged, and a declared key missing from the payload is refused (fail-closed).
  pub context_patch: Option<serde_json::Value>,
}

/// Outcome of [`crate::WorkflowService::signal`] / [`crate::WorkflowService::resubmit`].
#[derive(Debug, Clone)]
pub struct SignalOutcome {
  pub instance: WorkflowInstance,
  pub active_activities: Vec<ActivityInstance>,
  /// `true` = this `idempotency_key` was already processed; nothing advanced this call.
  pub replayed: bool,
}

/// Result of a read-only projection drift check.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionVerification {
  pub instance_id: uuid::Uuid,
  pub event_count: i64,
  pub consistent: bool,
  pub differences: Vec<String>,
}
