[package]
name = "fusion-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[lints]
workspace = true

[features]
default = ["with-postgres"]
with-postgres = ["sqlx/postgres"]
with-sqlite = ["sqlx/sqlite"]
with-uuid = ["dep:uuid", "fusion-sql-core/with-uuid"]

[dependencies]
fusion-common = { workspace = true }
fusion-sql-core = { workspace = true }
regex = { workspace = true }
serde.workspace = true
serde_json.workspace = true
log.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid = { workspace = true, optional = true }
duration-str = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
anyhow.workspace = true
logforth.workspace = true
