[package]
name = "fusions-security-example"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[[bin]]
name = "example-oauth2-github"
path = "src/example-oauth2-github.rs"

[[bin]]
name = "example-oauth2-gitee"
path = "src/example-oauth2-gitee.rs"

[[bin]]
name = "github-async"
path = "src/github-async.rs"

[[example]]
name = "gen-hash"
path = "src/gen-hash.rs"

[dependencies]
fusions = { workspace = true, features = ["oauth"] }
tokio = { workspace = true, features = ["full"] }
dotenvy = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
argon2 = { workspace = true }
