name: Rust

on:
  pull_request:
  push:
    branches: [main]

jobs:
  cargo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Format
        run: cargo fmt --all -- --check
      - name: Check
        run: cargo check --workspace
      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Test
        run: cargo test --workspace --all-targets --all-features

